### ISSUE TITLE
502 Bad Gateway and TypeError in JavaScript Code

### ISSUE THREAD

**Issue by jiawei-zhang-a** [robertjdominguez/ez-resy#5]
# Description
I am experiencing a 502 Bad Gateway error when accessing the resy. The issue appears to be related to the backend service, which is using nginx as a proxy server. 

<img width="837" alt="image" src="https://github.com/robertjdominguez/ez-resy/assets/31959109/a6567f97-f5df-4945-9fdf-985b35103e75">

# .env
VENUE_ID=4287
DATE=2024-07-03
EARLIEST=12:00
LATEST=20:00
PARTY_SIZE=3
PAYMENT_ID= 'I get it from the X-Amz-Cf-Id: in payment_method object'
AUTH_TOKEN='I get it from the cookie auth_token

**Comment by robertjdominguez** [comment]
I believe your issue is that you've selected the wrong value for `PAYMENT_ID`. You should:

1. Open the Network tab
2. Authenticate to Resy
3. Find a request to `https://api.resy.com/2/user`
4. Within that, search for `payment_methods` and take the `id` value 👈 this is what you want.

**Comment by jiawei-zhang-a** [comment]
Hi Rob, thank you so much! I have successfully booked a reservation. Very much thanks to your project! It is so important to me. BTW, I found the id in api.resy.com/3/auth not in https://api.resy.com/2/user which is kind of weird.
<img width="230" alt="image" src="https://github.com/robertjdominguez/ez-resy/assets/31959109/906f88ba-8e18-4650-975a-d580726d9c73">

**Comment by robertjdominguez** [comment]
Glad you got yourself sorted 👍
