### ISSUE TITLE
JWT token not found in the AUTH_TOKEN environment variable

### ISSUE THREAD

**Issue by sec12tst8r84** [robertjdominguez/ez-resy#7]
Hello, thank you for providing your script. This is my first time using Node.js and I installed it to run your script. I've followed your README instructions to the best of my ability but unfortunately I'm not much of a programmer. When I type run start, I get the following error: > resy@1.0.0 start
> ./env_manager.sh && dotenv -e .env node index.js

'.' is not recognized as an internal or external command,
operable program or batch file.

So I added the DATE line manually and did start:today but I've ended up with "JWT token not found in the AUTH_TOKEN environment variable" and I am unsure how to fix it.

Secondly, is there a way to run this script at a certain time? Thank you.

**Comment by robertjdominguez** [comment]
The configuration section
<https://github.com/robertjdominguez/ez-resy?tab=readme-ov-file#configuration>
walks through where to find the various values that are required for the
program to run.

To run this at a certain time, you'll need to use something called a cron
job: https://en.wikipedia.org/wiki/Cron

**Comment by sec12tst8r84** [comment]
Hi Robert, Thank you for replying. I've gotten my auth token by following the readme file. ![auth](https://github.com/user-attachments/assets/0f2fa547-988e-498c-8e78-3b28c208208b). Below is my env file. I've named it process.env.
![env](https://github.com/user-attachments/assets/20ffaba8-e847-41cb-894b-8de1757554c9)

**Comment by robertjdominguez** [comment]
The application expects the file to be called `.env`. You can learn more about Node.js and its use of environment files here: https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs

**Comment by sec12tst8r84** [comment]
Thank you very much! I misunderstood the readme. Thank you again for creating such a great program.
